//
//  GLTheme.h
//  GistList
//
//  Created by Aaron Geisler on 6/7/15.
//  Copyright (c) 2015 Apptivus. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface GLTheme : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* userAvatarTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginIconGithubTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginIconOfflineTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginGlLogoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginHeaderTwoFactorTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginHeaderSyncTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* taskGlLogoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* settingsIconArrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* settingIconCompletedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* loginIconVerifyTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* taskIconAddTargets;

// Colors
+ (UIColor*)buttonColorGreen;
+ (UIColor*)buttonColorBlue;
+ (UIColor*)buttonColorGray;
+ (UIColor*)buttonColorRed;
+ (UIColor*)backgroundColorDefault;
+ (UIColor*)backgroundColorEditText;
+ (UIColor*)backgroundColorSpinner;
+ (UIColor*)backgroundColorSettings;
+ (UIColor*)backgroundColorHeader;
+ (UIColor*)textColorDefault;
+ (UIColor*)textColorPlaceholder;
+ (UIColor*)textColorLabel;
+ (UIColor*)textColorSpinner;
+ (UIColor*)tileColorDivider;
+ (UIColor*)tileColorDefault;
+ (UIColor*)tileColorInactive;
+ (UIColor*)tileColorHighlight;

// Generated Images
+ (UIImage*)imageOfUserAvatar;
+ (UIImage*)imageOfLoginIconGithub;
+ (UIImage*)imageOfLoginIconOffline;
+ (UIImage*)imageOfLoginGlLogo;
+ (UIImage*)imageOfLoginHeaderTwoFactor;
+ (UIImage*)imageOfLoginHeaderSync;
+ (UIImage*)imageOfTaskGlLogo;
+ (UIImage*)imageOfSettingsIconArrow;
+ (UIImage*)imageOfSettingIconCompleted;
+ (UIImage*)imageOfLoginIconVerify;
+ (UIImage*)imageOfTaskIconAdd;

@end
